name: flutter_google_places_2
description: Google places autocomplete widgets for flutter.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.2.5
  http: ^1.2.2
  rxdart: ^0.28.0
  rxdart_ext: ^0.3.0
  listenable_stream: ^2.0.1
  collection: ^1.18.0
  flutter_bloc_pattern: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  assets:
    - packages/flutter_google_places_2/assets/google_black.png
    - packages/flutter_google_places_2/assets/google_white.png
